# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /nvme0n1/gaoruihao/zipline/Project-Zipline-FPGA/vitis-wrapper/cceip_wrapper/vivado_rtl_kernel/cceip_kernel_ex/cceip_kernel_ex.srcs/sources_1/ip/axi_apb_bridge_0/axi_apb_bridge_0.xci
# IP: The module: 'axi_apb_bridge_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /nvme0n1/gaoruihao/zipline/Project-Zipline-FPGA/vitis-wrapper/cceip_wrapper/vivado_rtl_kernel/cceip_kernel_ex/cceip_kernel_ex.srcs/sources_1/ip/axi_apb_bridge_0/axi_apb_bridge_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_apb_bridge_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /nvme0n1/gaoruihao/zipline/Project-Zipline-FPGA/vitis-wrapper/cceip_wrapper/vivado_rtl_kernel/cceip_kernel_ex/cceip_kernel_ex.srcs/sources_1/ip/axi_apb_bridge_0/axi_apb_bridge_0.xci
# IP: The module: 'axi_apb_bridge_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /nvme0n1/gaoruihao/zipline/Project-Zipline-FPGA/vitis-wrapper/cceip_wrapper/vivado_rtl_kernel/cceip_kernel_ex/cceip_kernel_ex.srcs/sources_1/ip/axi_apb_bridge_0/axi_apb_bridge_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_apb_bridge_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
